default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: artist_management_rails

test:
  <<: *default
  database: myapp_test
